version: "3.8"

services:
  api:
    container_name: no-smoking-bot
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb-image:27017/db-name
    build:
      context: .
      target: development
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
    command: npm run start:debug
    restart: always
    ports:
      - "9999:9999"
    depends_on:
      - mongodb-image
  mongodb-image:
    container_name: no-smoking-mongo
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
      - "27018:27018"
